config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :categories do
    resources :products do
      resources :reviews
    end
  end

  root 'categories#index'
  get '/users/:id' => 'users#show'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products, dependent: :destroy
  validates :name, presence:true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]
  
  expose(:categories)
  expose(:category)
  expose(:product) { Product.new }

  def index
  end

  def show
  end

  def new
    if !current_user.admin?
      redirect_to new_user_session_path
    end
  end

  def edit
    if !current_user.admin?
      redirect_to new_user_session_path
    end
  end

  def create
    if current_user.admin?
      
      self.category = Category.new(category_params)

      if category.save
        redirect_to category, notice: 'Category was successfully created.'
      else
        render action: 'new'
      end
    else
      redirect_to new_user_session_path
    end
    
  end

  def update
    if current_user.admin?
      if category.update(category_params)
        redirect_to category, notice: 'Category was successfully updated.'
      else
        render action: 'edit'
      end
    else
      redirect_to new_user_session_path
    end
  end

  def destroy
    if current_user.admin?
      category.destroy
      redirect_to categories_url, notice: 'Category was successfully destroyed.'
    end
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= form_for category do |f|
  - if category.errors.any?
    #error_explanation
      %h2= "#{pluralize(category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - category.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-default'

app/views/categories/edit.html.haml
%h1 Editing category

- if current_user.admin?
  = render 'form'

\|
= link_to 'Back', categories_path, class: 'btn btn-primary'
%p

app/views/categories/index.html.haml
%h1 Listing categories

%table.table.table-hover
  %tr
    %th Name
    %th
    %th
    %th

  - categories.each do |category|
    %tr
      %td= category.name
      %td= link_to 'Show', category
      - if user_signed_in? && current_user.admin?
        %td= link_to 'Edit', edit_category_path(category) 
        %td= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } 

%br

= link_to 'New Category', new_category_path if user_signed_in? && current_user.admin?

%p
%br/

app/views/categories/new.html.haml
%h1 New category

= render 'form'
\|
= link_to 'Back', categories_path, class: 'btn btn-primary'
%p
%br/

app/views/categories/show.html.haml
%p
  %h2
    Category:
    %b
      = category.name
    %hr

%p
  - category.products.each do |product|
    %ul
      = link_to product.title, category_product_path(product.category, product), {:style=>"border: none;"}

%p
  - if user_signed_in? 
    %h3 New product
    = render 'products/form'
    \|
    
    = link_to 'Back', categories_path, class: 'btn btn-primary'