config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :categories do
    resources :products do
      resources :reviews
    end
  end

  root 'categories#index'
  get '/users/:id' => 'users#show'
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :reviews, dependent: :destroy
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, format: { :with => /\A\d+(?:\.\d{0,2})?\z/ }, numericality: true
  
  def average_rating
    #review_sum = reviews.map(:rating).reduce(:+)
    review_sum = reviews.inject(0) { |sum, review| sum += review.rating }
    return review_sum == 0? 0 : (review_sum.to_f / reviews.count) 
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  expose(:category)
  expose(:products)
  expose(:product)
  expose(:review) { Review.new }
  expose_decorated(:reviews, ancestor: :product)

  def index
  end

  def show
  end

  def new
  end

  def edit
    if current_user != product.user
      flash[:error] = "You are not allowed to edit this product."
      redirect_to category_product_url
    end
  end

  def create
    if user_signed_in?
      self.product = Product.new(product_params)
      product.user = current_user

      if product.save
        category.products << product
        redirect_to category_product_url(category, product), notice: 'Product was successfully created.'
      else
        render action: 'new'
      end
    else
      redirect_to new_user_session_path
    end
  end

  def update
    if current_user != product.user
      flash[:error] = "You are not allowed to edit this product."
      redirect_to category_product_url
    elsif user_signed_in?
      if self.product.update(product_params)
        redirect_to category_product_url(category, product), notice: 'Product was successfully updated.'
      else
        render action: 'edit'
      end
    else
      redirect_to new_user_session_path
    end
  end

  # DELETE /products/1
  def destroy
    if user_signed_in? 
      if current_user == product.user || current_user.admin?
        product.destroy
        redirect_to category_url(product.category), notice: 'Product was successfully destroyed.'
      else
        redirect_to category_url(product.category), notice: 'You are not allowed to delete this product'
      end
    else
      redirect_to new_user_session_path 
    end
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :category_id)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for [category, product] do |f|
  - if product.errors.any?
    #error_explanation
      %h2= "#{pluralize(product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - product.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  .form-group
    = f.label :price
    = f.text_field :price, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-primary pull-left'

app/views/products/edit.html.haml
- if user_signed_in? && current_user == product.user
  %h1 Editing product

  = render 'form'

  \|

  = link_to 'Back', category_product_path(category, product), class: 'btn btn-primary'
%p
%br/

app/views/products/index.html.haml
%h1 Listing products

%table.table.table-hover
  %tr
    %th Title
    %th Description
    %th Price
    %th
    %th
    %th

  - products.each do |product|
    %tr
      %td= product.title
      %td= product.description
      %td= product.price
      %td= link_to 'Show', category_product_path(product.category, product) 
      %td= link_to 'Edit', edit_category_product_path(product.category, product) if user_signed_in? 
      %td= link_to 'Destroy', category_product_path(product.category, product), method: :delete, data: { confirm: 'Are you sure?' } if user_signed_in? 

%br

app/views/products/new.html.haml
- if user_signed_in? && current_user == product.user
  %h1 New product

  = render 'form'
  \|
  = link_to 'Back', category_products_path, class: "btn btn-primary"
%p
%br/

app/views/products/show.html.haml
%p
  %h3
    %b= product.title
  %hr
%p
  %b Description:
  = product.description
%p
  %b Price:
  $
  = product.price
%p
  %b Rating:
  = '%.2f' % product.average_rating
  out of 5  
%p
  %b Category
  = product.category.name
%hr
-if user_signed_in?
  %h3 Review this product

= render 'reviews/form'

%h3
  = product.reviews.count 
  Reviews
  
= render reviews

%br/


= link_to 'Back', category_products_path, class: 'btn btn-primary' 
%p